name: ADF Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install packages
      run: npm install

    - name: Validate ADF
      run: |
        npm run build validate ../ \
        /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_DEV }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV }}

    - name: Generate ARM
      run: |
        npm run build export ../ \
        /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_DEV }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV }} \
        ExportedArmTemplate

    - uses: actions/upload-artifact@v4
      with:
        name: adf-arm
        path: build/ExportedArmTemplate
