name: Deploy SIT

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-sit:
    name: Deploy SIT
    runs-on: ubuntu-latest
    environment: SIT

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Download Latest Release Asset
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: ExportedArmTemplate.zip
          out-file-path: .
          
      - name: Extract ARM Template
        run: |
          unzip -o ExportedArmTemplate.zip

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Verify Azure Login
        run: az account show

      - name: Run Pre Deployment Script
        uses: azure/powershell@v3
        with:
          azPSVersion: latest
          inlineScript: ./scripts/PrePostDeploymentScript.Ver2.ps1 -armTemplate "./ExportedArmTemplate/ARMTemplateForFactory.json" -armTemplateParameters "./ExportedArmTemplate/ARMTemplateParametersForFactory.json" -ResourceGroupName "${{ secrets.RG_SIT }}" -DataFactoryName "${{ secrets.ADF_SIT }}" -predeployment $true -deleteDeployment $false

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RG_SIT }}
          template: ExportedArmTemplate/ARMTemplateForFactory.json
          parameters: ExportedArmTemplate/ARMTemplateParametersForFactory.json

      - name: Run Post Deployment Script
        uses: azure/powershell@v3
        with:
          azPSVersion: latest
          inlineScript: ./scripts/PrePostDeploymentScript.Ver2.ps1 -armTemplate "./ExportedArmTemplate/ARMTemplateForFactory.json" -armTemplateParameters "./ExportedArmTemplate/ARMTemplateParametersForFactory.json" -ResourceGroupName "${{ secrets.RG_SIT }}" -DataFactoryName "${{ secrets.ADF_SIT }}" -predeployment $false -deleteDeployment $true
