name: Deploy Azure Data Factory

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

################################################################################
# BUILD
################################################################################

  build:

    name: Build ARM Template

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Packages
        run: npm install

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Login
        run: az account show

      - name: Validate ADF
        run: npm run build validate ${{github.workspace}}/adf/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_DEV }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV }} # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 

      - name: Generate ARM Template
        run: npm run build export ${{github.workspace}}/adf/ /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_DEV }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV }} "ExportedArmTemplate"  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 

      - name: Verify ARM Template
        run: |
          ls -R ExportedArmTemplate

      - name: Upload ARM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: adf-arm
          path: ExportedArmTemplate

################################################################################
# DEPLOY DEV
################################################################################

  deploy-dev:

    name: Deploy DEV

    needs: build

    runs-on: ubuntu-latest

    environment: DEV

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Download ARM Artifact
        uses: actions/download-artifact@v4
        with:
          name: adf-arm
          path: ExportedArmTemplate

      - name: Verify Download
        shell: pwsh
        run: |
          Write-Host "Repository structure:"
          Get-ChildItem -Recurse

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Login
        run: az account show

      - name: Run Pre Deployment Script
        shell: pwsh
        run: |
          ./scripts/PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "./ExportedArmTemplate/ARMTemplateForFactory.json" `
            -ResourceGroupName "${{ secrets.RG_NAME }}" `
            -DataFactoryName "${{ secrets.ADF_NAME }}" `
            -predeployment $true `
            -deleteDeployment $false

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          template: ExportedArmTemplate/ARMTemplateForFactory.json
          parameters: ExportedArmTemplate/ARMTemplateParametersForFactory.json

      - name: Run Post Deployment Script
        shell: pwsh
        run: |
          ./scripts/PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "./ExportedArmTemplate/ARMTemplateForFactory.json" `
            -ResourceGroupName "${{ secrets.RG_NAME }}" `
            -DataFactoryName "${{ secrets.ADF_NAME }}" `
            -predeployment $false `
            -deleteDeployment $true
